#configure the wisdom system
providers: [Coursera]
storage_engines: [SQL, MongoDB]

storage_configs:
    MongoDB:
        db: wisdom
        unit_test_collection: unit_tests
    SQL:
        connection_string: postgresql://wisdom_backend:wisdom_backend@localhost/wisdom